import { Inter } from "next/font/google";
import "./globals.css";
import AppBarComponent from "../components/AppBar";
import { CookiesProvider } from 'next-client-cookies/server';
import StoreProvider from "./StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <CookiesProvider>
            <AppBarComponent />
            {children}
          </CookiesProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
